### ISSUE TITLE
2.4.1 Beta 2 Release Checklist

### ISSUE THREAD

**Issue by TOoSmOotH** [Security-Onion-Solutions/securityonion#10191]
This release checklist is important for ensuring consistently high-quality releases are provided to the user base. The checklist is relevant for all release types.

Prepare release (must be done in order and typically needs to start the day before release day)
- [ ] If releasing a non-dev branch, create new GitHub project (skip for hotfixes)
- [ ] If releasing a non-dev branch, create the new branch (use hotfix/2.x.y for hotfixes, or patch/2.x.y for full patch releases)
- [ ] If releasing a non-dev branch, update the VERSION file to the next minor increment (Ex: 2.3.72 -> 2.3.73) (Or update HOTFIX file for hotfixes)
- [ ] If releasing a non-dev branch, clear out HOTFIX file (skip for hotfixes)
- [ ] If releasing a non-dev branch, create new pipeline based on the new branch (consider images, soc, and main repos)
- [ ] If necessary, update Kibana dashboards and index patterns (IMPORTANT: remember to  escalate at least one alert first)
- [ ] Update `soup` script for new release. Note: If updating Kibana dashboards and index patterns, make sure that `soup` will apply those updates as necessary
- [ ] If doing a full release, use a recent nightly ISO build to generate a full screenshot run
- [ ] Ensure all affected RTD pages are updated including screenshots
- [ ] Update release notes - Search ISO build output for "TODO" after all issues have been closed and at least one ISO has then built
- [ ] Confirm all code changes have been pushed (do not rely on the commit date for this, since a push this morning could contain commits from several days ago)
- [ ] Build final SOC image, ensuring it's using the commit with the updated release notes (this can be skipped for hotfixes OR if allowing the normal build process to run after hours)
- [ ] Build final ISO and cloud images (skip cloud images for hotfixes) after the above SOC image finishes building (these builds can be concurrent). (This can be skipped if allowing the normal build process to run after hours)
- [ ] Pause ISO and cloud images jobs (this can be skipped if allowing the normal build process to run after hours)
- [ ] Allow all automated tests to run on the final builds
- [ ] Verify all automated tests are passing
- [ ] Pause build pipeline

Test
- [ ] Review logs (Run the following command and review any errors: `{ sudo docker ps -q | xargs -I nn docker logs -n 100 nn 2>&1 && sudo find /opt/so/log/ /nsm/zeek/logs/ /nsm/strelka/log/ /nsm/wazuh/logs/ /nsm/osquery/ -type f -exec tail -n 100 {} \;; } | grep -i error | grep -vEi "connect|eof|_ml|iteration|communication packets|use of closed|bookkeeper|NoIndices|Failed to start transient scope|Status 200|so-user.lock exists|systemd-run|retcode: 1|telemetry-task|redisqueue|fleet_detail_query|unavailable|num errors=0|elastalert_error.json|provisioning/alerting|provisioning/notifiers|provisioning/plugins|database is locked|error: '0'|active-responses.log"`
- [ ] Verify Curator config and no errors in log ()
- [ ] Verify pfSense firewall log parsing ()
- [ ] Verify Strelka file extraction works with both Suricata and Zeek (use so-test to verify) ()
- [ ] Analyst Workstation Install Network ()
- [ ] Airgap Upgrade Standalone - 8009 ()
- [ ] Airgap Upgrade Distributed - 8010-8012 ()
- [ ] Network Upgrade Distributed - 8003-8005 ()
- [ ] Managersearch and Heavynode - 8007 - 8008 ()
- [ ] Network Upgrade Eval - 8006 ()
- [ ] Network Upgrade Standalone Ubuntu 20 - 8000 ()
- [ ] Network Upgrade Standalone Ubuntu 18 - 8001 ()
- [ ] Network Upgrade Standalone CentOS 7 - 8002 ()
- [ ] Network Upgrade Import so-import-pcap and so-import-evtx ()
- [ ] Upgrade Staging (MKR)
- [ ] Upgrade Production ()
- [ ] AMI installation (skip for hotfixes)
- [ ] AZI installation (skip for hotfixes)
- [ ] GCI installation (skip for hotfixes)
- [ ] WebApp Security Tests ()

ISO Prep (**DO NOT START THIS STEP** until the "Prepare release" steps have been completed)
- [ ] .sig is added to GitHub
- [ ] Hashes are updated in GitHub - Search ISO build output for "TODO"
- [ ] README.md is updated with new version and, if necessary, new screenshots
- [ ] Correct date in VERIFY_ISO.md
- [ ] ISO is uploaded
- [ ] ISO download speed check

Build and Project Maintenance
- [ ] Repeat for the following repositories:  so, soc, images, tests, build (only `so` for hotfixes)
  - [ ] Create PR to master for the changes
  - [ ] Merge PR to master for changes
  - [ ] If releasing a patch or hotfix branch, merge master into dev
  - [ ] Remove obsolete branches
  - [ ] Create GitHub release or tag repo with version
- [ ] If releasing dev branch, bump VERSION in dev branch
- [ ] If releasing dev branch, create new pipeline for next release
- [ ] Archive build pipeline (skip for hotfixes)
- [ ] If releasing dev branch, create the next GitHub project
- [ ] Verify the project issues are in their correct state and all unworked issues are moved out of the project
- [ ] Close GitHub project (skip for hotfixes)

Distribution
- [ ] Educate extended group on new release
- [ ] Publish AWS Image to Marketplace (skip for hotfixes)
- [ ] Publish Azure Image to Marketplace (skip for hotfixes)
- [ ] Publish notices (Twitter, GitHub, Blog - tag as release, etc)
- [ ] Kickoff website job (skip for hotfixes)
