### ISSUE TITLE
Create release checklist to be followed for all releases

### ISSUE THREAD

**Issue by jertel** [Security-Onion-Solutions/securityonion#1048]
This release checklist is important for ensuring consistently high-quality releases are provided to the user base. The checklist is relevant for both Upgrades and Patches.

Test multiple variations within each category:  Eval, Standalone, Distributed, Import
- [x] ISO Installation
- [x] Network Installation
- [x] ISO Upgrade
- [x] Network Upgrade
- [x] Upgrade Production

Documentation
- [x] All affected RTD pages are updated
- [x] Update release notes
- [x] changes.json is updated
- [x] README.md is updated

ISO Prep
- [x] .sig is added to GitHub
- [x] Hashes are updated in GitHub

Merge Branches (securityonion, securityonion-images, securityonion-soc repositories)
- [x] Create PR for the changes
- [x] Assign two reviewers (need to double-check changes for all patches)
- [x] Merge working branch into master
- [NA] If working branch is not 'dev', merge master into dev (primarily for patches)
- [x] Remove obsolete branches
- [x] Create GitHub release

Builds
- [x] Create new pipeline for next release

ISO Distribution
- [x] ISO is uploaded to BackBlaze
- [x] ISO download link is created
- [x] ISO download speed is good and completes successfully
- [x] Remove access to old ISOs

Cloud Images
- [NA] Enable public access of new AMI 
- [NA] Copy new AMI out to regions: London, Frankfurt, Virginia, Oregon
- [NA] Disable access to deprecated cloud images

Social
- [x] Blog post
- [x] Twitter
- [x] Reddit
- [x] Google Groups
