### ISSUE TITLE
Playbook Fixes

### ISSUE THREAD

**Issue by defensivedepth** [Security-Onion-Solutions/securityonion#1064]
- [ ] GA - Require `level` for alerting queue (Currently defaults to medium if no level is defined in Sigma)
- [ ] GA - Hardcoded admin password
- [ ] GA - Hardcoded automation password/api key
- [ ] ESAlerter Pivots - Playbook, Kibana & SOC
- [x] Sigma Editor bug - asterisks/slash
- [x]  Triage - Fix Navigator layer updating
- [x] Change default imports to Sysmon/WEL & document
- [x] ElastAlert tuning - change search time from 10min to 5min
- [x] ESAlerter - search across clusters
- [x] ESAlerter Mapping conflict - change `data` to `event_data`
- [x] TheHive alerter bug - mapping mismatch? 
- [x] RC3 - Implement new sigmac mappings for new field type
