### ISSUE TITLE
2.4.60 Release Checklist

### ISSUE THREAD

**Issue by jertel** [Security-Onion-Solutions/securityonion#12580]
This release checklist is important for ensuring consistently high-quality releases are provided to the user base. The checklist is relevant for all release types.

Prepare release (must be done in order and typically needs to start the day before release day)
- [N/A] If releasing a non-dev branch, create new GitHub milestone
- [N/A] If releasing a non-dev branch, create the new branch (use hotfix/2.x.y for hotfixes, or patch/2.x.y for full patch releases)
- [N/A] If releasing a non-dev branch, update the VERSION file to the next minor increment (Ex: 2.3.72 -> 2.3.73) (Or update HOTFIX file for hotfixes)
- [N/A] If releasing a non-dev branch, clear out HOTFIX file (skip for hotfixes)
- [N/A] If releasing a non-dev branch, create new pipeline based on the new branch (consider images, soc, and main repos)
- [N/A] If necessary, update Kibana dashboards and index patterns (IMPORTANT: remember to  escalate at least one alert first)
- [x] Update `soup` script for new release. Note: If updating Kibana dashboards and index patterns, make sure that `soup` will apply those updates as necessary
- [x] Confirm WebApp Security Tests show no critical vulnerabilities
- [N/A] (2.3 only) Confirm network based soups are completing without error
- [x] If doing a full release, use a recent nightly ISO build to generate a full screenshot run
- [x] Update release notes - Search ISO build output for "TODO"
- [x] Confirm all affected RTD pages are updated including screenshots
- [x] Confirm all issues in the release notes are closed.
- [x] Confirm final SOC image build used the commit with the updated release notes (this can be skipped for hotfixes)
- [x] Validate the final ISO successfully built, and, if not a hotfix, includes latest SOC image
- [x] [2.4 only] Validate the final cloud images build (skip for hotfixes)
- [x] Boot ISO, choose IDH grub entry, follow prompts, and confirm it fully boots to login prompt (full setup not required)
- [x] Boot ISO, choose Desktop grub entry, follow prompts, and confirm it fully boots to login prompt (full setup not required)
- [x] Confirm all automated tests are passing
- [x] Pause build pipeline

Final Verification
- [N/A] (2.3 only) Manual testing
- [x] (2.4 only) Upgrade Staging (MKR)
- [x] (2.4 only) Upgrade Production ()

Let code marinate for 2 days

ISO Prep (**DO NOT START THIS STEP** until the "Prepare release" steps have been completed)
- [x] .sig is added to GitHub
- [x] Hashes are updated in GitHub - Search ISO build output for "TODO"
- [x] README.md is updated with new version and, if necessary, new screenshots
- [x] Correct date in DOWNLOAD_AND_VERIFY_ISO.md
- [x] ISO is uploaded
- [x] ISO download speed check

Build and Project Maintenance
- [x] Repeat for the following repositories:  so, soc, images, tests, build (only `so` for hotfixes)
  - [x] Create PR to master (2.3) or 2.4/main for the changes
  - [x] Obtain approvals and merge PR
  - [N/A] If releasing a patch or hotfix branch, merge backwards into dev
  - [x] Remove obsolete branches
  - [x] Create GitHub release or tag repo with version
- [x] (2.4 only) Create link to the ISO download page for the latest GitHub release (only on securityonion repo)
- [x] If releasing dev branch, bump VERSION in dev branch
- [x] If releasing dev branch, create new pipeline for next release
- [x] Archive build pipeline (skip for hotfixes)

Distribution
- [x] Educate extended group on new release
- [x] Publish notices (Twitter, GitHub, Blog - tag as release, etc)
- [x] (2.4 only) Publish AWS Image to Marketplace (skip for hotfixes)
- [x] (2.4 only) Publish Azure Image to Marketplace (skip for hotfixes)
- [x] (2.4 only) Publish Google Image to Marketplace (skip for hotfixes)
- [x] (2.4 only) Kickoff website job (skip for hotfixes)
- [ ] (2.4 only) Consider uploading image to MBX for appliances
