### ISSUE TITLE
Release Checklist 2.3.10

### ISSUE THREAD

**Issue by jertel** [Security-Onion-Solutions/securityonion#1625]
This release checklist is important for ensuring consistently high-quality releases are provided to the user base. The checklist is relevant for both Upgrades and Patches.

Finalize release content
- [x] Update Kibana dashboards and index patterns (IMPORTANT: remember to  escalate at least one alert first)

Test
- [x] ISO Installation Eval (JB)
- [x] ISO Installation Distributed (MR)
- [x] ISO Installation Import (JE)
- [x] ISO Installation Standalone
- [x] Network Installation Eval (WW - CentOS)
- [x] Network Installation Standalone
- [x] Network Installation Distributed (WW - 1 known issue)
- [x] Network Installation Import (MR)
- [x] Network Installation Analyst (MR)
- [x] Airgap Installation
- [x] Airgap Upgrade Standalone
- [x] Airgap Upgrade Distributed
- [x] Network Upgrade Eval (WW)
- [x] Network Upgrade Standalone (MR)
- [x] Network Upgrade Distributed (JP - Ubuntu)
- [x] Network Upgrade Import (JE - 2.3.2 -> 2.3.10)
- [x] Upgrade Production

Documentation
- [x] All affected RTD pages are updated
- [x] Update release notes
- [x] changes.json is updated
- [x] README.md is updated

ISO Prep
- [x] .sig is added to GitHub
- [x] Hashes are updated in GitHub

Revision Control (builds, soc, images, tests)
- [x] Create and merge PR for the changes
- [x] If patch, merge master into dev
- [x] Remove obsolete branches
- [x] Create GitHub release or tag repo with version
- [x] Repeat for all repositories

Builds
- [x] Pause build pipeline
- [x] If not a patch, create new pipeline for next release
- [x] If not a patch, bump VERSION in dev branch

ISO Distribution
- [x] ISO is uploaded
- [x] ISO download link is created
- [x] ISO download speed check
- [x] Remove access to old ISOs
- [x] Kickoff website job

Social
- [x] Blog post
- [x] Twitter
- [x] GitHub Discussions
- [x] Google Groups

Finish
- [x] Close GitHub project
