### ISSUE TITLE
Release Checklist 2.3.3

### ISSUE THREAD

**Issue by jertel** [Security-Onion-Solutions/securityonion#1830]
This release checklist is important for ensuring consistently high-quality releases are provided to the user base. The checklist is relevant for both Upgrades and Patches.

Finalize release content
- [x] Update Kibana dashboards and index patterns (IMPORTANT: remember to  escalate at least one alert first)

Test multiple variations within each category:  Eval, Standalone, Distributed, Import
- [x] ISO Installation
- [x] Network Installation
- [x] Airgap Upgrade
- [x] Network Upgrade
- [ ] Upgrade Production

Documentation
- [ ] All affected RTD pages are updated
- [ ] Update release notes
- [x] changes.json is updated
- [x] README.md is updated

ISO Prep
- [ ] .sig is added to GitHub
- [ ] Hashes are updated in GitHub

Revision Control (builds, soc, images, tests)
- [ ] Create and merge PR for the changes
- [ ] If patch, merge master into dev
- [ ] Remove obsolete branches
- [ ] Create GitHub release or tag repo with version
- [ ] Repeat for all repositories

Builds
- [ ] Pause build pipeline
- [ ] If not a patch, create new pipeline for next release
- [ ] If not a patch, bump VERSION in dev branch

ISO Distribution
- [ ] ISO is uploaded
- [ ] ISO download link is created
- [ ] ISO download speed check
- [ ] Remove access to old ISOs
- [ ] Kickoff website job

Social
- [ ] Blog post
- [ ] Twitter
- [ ] GitHub Discussions
- [ ] Google Groups

**Comment by jertel** [comment]
Abandoned this release.
