### ISSUE TITLE
2.3.20 Release Checklist

### ISSUE THREAD

**Issue by TOoSmOotH** [Security-Onion-Solutions/securityonion#2351]
This release checklist is important for ensuring consistently high-quality releases are provided to the user base. The checklist is relevant for both Upgrades and Patches.

Finalize release content
- [x] Update Kibana dashboards and index patterns (IMPORTANT: remember to  escalate at least one alert first)

Test
- [x] ISO Installation Eval (JE)
- [x] ISO Installation Distributed (WW)
- [x] ISO Installation Distributed True Cluster (MKR)
- [x] ISO Installation Import (JE)
- [x] ISO Installation Standalone (Auto)
- [x] Network Installation Eval (JE)
- [x] Network Installation Standalone (WW)
- [x] Network Installation Distributed (WW)
- [x] Network Installation Distributed True Cluster (JPP)
- [x] Network Installation Import (JPP)
- [x] Network Installation Analyst (JPP)
- [x] Network Installation Helix (WW)
- [x] Airgap Installation (MKR)
- [x] Airgap Distributed Install (MKR)
- [x] Airgap Upgrade Standalone (MKR)
- [x] Airgap Upgrade Distributed (MKR)
- [x] Network Upgrade Eval (JE)
- [x] Network Upgrade Standalone (JPP)
- [x] Network Upgrade Standalone Features (MKR)
- [x] Network Upgrade Distributed (MKR)
- [x] Network Upgrade Import (JPP)
- [x] Upgrade Production (MKR)

Documentation
- [x] All affected RTD pages are updated
- [x] Update release notes
- [x] changes.json is updated
- [x] README.md is updated

ISO Prep
- [x] .sig is added to GitHub
- [x] Hashes are updated in GitHub

Revision Control (builds, soc, images, tests)
- [x] Create and merge PR for the changes
- [x] If patch, merge master into dev
- [x] Remove obsolete branches
- [x] Create GitHub release or tag repo with version
- [x] Repeat for all repositories

Builds
- [x] Pause build pipeline
- [x] If not a patch, create new pipeline for next release
- [x] If not a patch, bump VERSION in dev branch

ISO Distribution
- [x] ISO is uploaded
- [x] ISO download link is created
- [x] ISO download speed check
- [x] Remove access to old ISOs
- [x] Kickoff website job

Social
- [x] Blog post
- [x] Twitter
- [x] GitHub Discussions
- [x] Google Groups

Finish
- [x] Close GitHub project
