### ISSUE TITLE
Release Checklist 2.3.30

### ISSUE THREAD

**Issue by jertel** [Security-Onion-Solutions/securityonion#3083]
This release checklist is important for ensuring consistently high-quality releases are provided to the user base. The checklist is relevant for both Upgrades and Patches.

Finalize release content
- [x] Update Kibana dashboards and index patterns (IMPORTANT: remember to  escalate at least one alert first)

Test
- [x] Analyst Workstation Install ISO (JPP)
- [x] Analyst Workstation Install Network (JPP)
- [x] Airgap Upgrade Standalone(MKR)
- [x] Airgap Upgrade Distributed(MKR)
- [x] Network Upgrade Eval (JPP)
- [x] Network Upgrade Standalone (JPP)
- [x] Network Upgrade Standalone Features (WW)
- [x] Network Upgrade Distributed (WW)
- [x] Network Upgrade Import (WW)
- [x] Upgrade Production (MKR)

Documentation
- [x] All affected RTD pages are updated
- [x] Update release notes
- [x] changes.json is updated
- [x] README.md is updated

ISO Prep
- [x] .sig is added to GitHub
- [x] Hashes are updated in GitHub

Revision Control (builds, soc, images, tests)
- [x] Create and merge PR for the changes
- [x] If patch, merge master into dev
- [x] Remove obsolete branches
- [x] Create GitHub release or tag repo with version
- [x] Repeat for all repositories

Builds
- [x] Pause build pipeline
- [x] If not a patch, create new pipeline for next release
- [x] If not a patch, bump VERSION in dev branch

ISO Distribution
- [x] ISO is uploaded
- [x] ISO download link is created
- [x] ISO download speed check
- [x] Remove access to old ISOs
- [x] Kickoff website job

Social
- [x] Blog post
- [x] Twitter
- [x] GitHub Discussions
- [x] Google Groups

Finish
- [ ] Close GitHub project

**Comment by TOoSmOotH** [comment]
WooHoo!!
