### ISSUE TITLE
2.3.51 Release Checklist

### ISSUE THREAD

**Issue by jertel** [Security-Onion-Solutions/securityonion#4230]
This release checklist is important for ensuring consistently high-quality releases are provided to the user base. The checklist is relevant for both Upgrades and Patches.

Finalize release content
- [NA] Update Kibana dashboards and index patterns (IMPORTANT: remember to  escalate at least one alert first)

Test
- [NA] Analyst Workstation Install ISO ()
- [NA] Analyst Workstation Install Network ()
- [NA] Airgap Upgrade Standalone()
- [x] Airgap Upgrade Distributed()
- [NA] Network Upgrade Distributed ()
- [NA] Network Upgrade Eval ()
- [NA] Network Upgrade Standalone ()
- [NA] Network Upgrade Import ()
- [x] Upgrade Production ()
- [x] AMI installation ()

Documentation
- [NA] All affected RTD pages are updated
- [x] Update release notes - Search ISO build output for "TODO"
- [x] README.md is updated

ISO Prep
- [x] .sig is added to GitHub
- [x] Hashes are updated in GitHub - Search ISO build output for "TODO"

Revision Control (builds, soc, images, tests)
- [x] Create and merge PR for the changes
- [x] If patch, merge master into dev
- [x] Remove obsolete branches
- [x] Create GitHub release or tag repo with version
- [x] Repeat for all (4) repositories

Builds
- [x] Pause build pipeline
- [NA] If not a patch, create new pipeline for next release
- [NA] If not a patch, bump VERSION in dev branch

ISO Distribution
- [x] ISO is uploaded
- [x] ISO download speed check
- [x] Remove access to old ISOs
- [x] Kickoff website job

Cloud Distribution
- [x] Publish AMI 

Social
- [x] Blog post
- [x] Twitter
- [x] GitHub Discussions

Finish
- [x] Close GitHub project
