### ISSUE TITLE
2.3.60 Release Checklist

### ISSUE THREAD

**Issue by jertel** [Security-Onion-Solutions/securityonion#4618]
This release checklist is important for ensuring consistently high-quality releases are provided to the user base. The checklist is relevant for both Upgrades and Patches.

Finalize release content
- [x] Update Kibana dashboards and index patterns (IMPORTANT: remember to  escalate at least one alert first)

Test
- [x] Analyst Workstation Install ISO (RWW)
- [x] Analyst Workstation Install Network (DLB)
- [x] Airgap Upgrade Standalone(MKR)
- [x] Airgap Upgrade Distributed(MKR)
- [x] Network Upgrade Distributed (RWW)
- [x] Network Upgrade Eval (DLB)
- [x] Network Upgrade Standalone (MKR)
- [x] Network Upgrade Import (RWW)
- [x] Upgrade Production (MKR)
- [x] AMI installation (JBE)

Documentation
- [x] All affected RTD pages are updated
- [x] Update release notes - Search ISO build output for "TODO"
- [x] README.md is updated

ISO Prep
- [x] .sig is added to GitHub
- [x] Hashes are updated in GitHub - Search ISO build output for "TODO"

Revision Control (builds, soc, images, tests)
- [x] Create and merge PR for the changes
- [NA] If patch, merge master into dev
- [x] Remove obsolete branches
- [x] Create GitHub release or tag repo with version
- [x] Repeat for all (4) repositories

Builds
- [x] Pause build pipeline
- [x] If not a patch, create new pipeline for next release
- [x] If not a patch, bump VERSION in dev branch

ISO Distribution
- [x] ISO is uploaded
- [x] ISO download speed check
- [x] Remove access to old ISOs
- [x] Kickoff website job

Cloud Distribution
- [x] Publish AMI 

Social
- [x] Blog post
- [x] Twitter
- [x] GitHub Discussions

Finish
- [x] Close GitHub project
