### ISSUE TITLE
2.3.60 HEAVYNODE HotFix Checklist

### ISSUE THREAD

**Issue by jertel** [Security-Onion-Solutions/securityonion#4713]
Checklist for creating a hotfix. Note that hotfixes are only available for fixes that do not require image builds.

- [x] Branch securityonion master project
- [x] Push fix to branch
- [x] Add unique, identifier to represent the `HOTFIX` file. Ex: XYZCRONJOBFIX. If a hotfix is already defined, add the new hotfix after it, on the same line, separated by a space.
- [x] Manual test hotfix from branch using `BRANCH=myhotfixbranch soup`
- [x] If pipeline still in place, run a network installation test from previous release pipeline.
- [x] Run soup on persistent environments via hotfix branch
- [x] Create and merge PR from hotfix branch to master
- [NA] Merge master back to dev
- [x] Create GitHub release for the hotfix
- [x] Add new hotfix release to the `releasenotes.rst` file for 2.x
- [x] Socials
