### ISSUE TITLE
2.3.60 FBPIPELINE Hotfix Checklist

### ISSUE THREAD

**Issue by jertel** [Security-Onion-Solutions/securityonion#4787]
Checklist for creating a hotfix. Note that hotfixes are only available for fixes that do not require image builds.

- [x] Branch securityonion master project into a `hotfix/2.?.??` branch
- [x] Submit PR with fix to the hotfix branch
- [x] Add unique identifier to the `HOTFIX` file. Ex: _HEAVYNODE_. If a hotfix is already defined, add the new hotfix after it, on the same line, separated by a space.
- [x] Manual test hotfix from branch using `BRANCH=hotfix/2.?.?? soup`
- [x] Add new hotfix release to the `releasenotes.rst` file for 2.x
- [x] Update docs to reflect any changes, additions, or deletions
- [x] Create hotfix pipeline (can reuse the same pipeline for all hotfixes of a specific version)
- [x] Build final ISO via pipeline
- [x] Launch automated tests for the hotfix
- [x] Run soup on persistent environments via hotfix branch
- [x] Rename ISO and SIG files to include the hotfix suffix
- [x] Upload ISO
- [x] Update VERIFYISO.md with new ISO URL and SIG info
- [x] Push new SIG file
- [x] Validate ISO download speeds
- [x] Create and merge PR from hotfix branch to master
- [x] Merge master back to dev
- [x] Create GitHub release for the hotfix
- [x] Socials
