### ISSUE TITLE
2.3.61 Release Checklist

### ISSUE THREAD

**Issue by jertel** [Security-Onion-Solutions/securityonion#4882]
This release checklist is important for ensuring consistently high-quality releases are provided to the user base. The checklist is relevant for both Upgrades and Patches.

Prepare release
- [x] If releasing a non-dev branch, create new GitHub project.
- [x] If releasing a non-dev branch, create the new branch.
- [x] If releasing a non-dev branch, update the VERSION file to the next minor increment (Ex: 2.3.72 -> 2.3.73)
- [x] If releasing a non-dev branch, clear out HOTFIX file.
- [x] If releasing a non-dev branch, create new pipeline based on the new branch (consider images, soc, and main repos)
- [NA] Update Kibana dashboards and index patterns (IMPORTANT: remember to  escalate at least one alert first)

Test
- [x] Analyst Workstation Install Network (JPP)
- [x] Airgap Upgrade Standalone(MKR)
- [NA] Airgap Upgrade Distributed()
- [x] Network Upgrade Distributed (MKR)
- [NA] Network Upgrade Eval ()
- [x] Network Upgrade Standalone (DLB)
- [NA] Network Upgrade Import ()
- [x] Upgrade Production (MKR)
- [x] AMI installation (JBE)

Documentation
- [NA] All affected RTD pages are updated
- [x] Update release notes - Search ISO build output for "TODO" after all issues have been closed and at least one ISO has then built.
- [x] README.md is updated

ISO Prep
- [x] .sig is added to GitHub
- [x] Hashes are updated in GitHub - Search ISO build output for "TODO"

Revision Control (builds, soc, images, tests)
- [x] Create and merge PR to master for the changes
- [x] If releasing a non-dev branch, merge master into dev
- [x] Remove obsolete branches
- [x] Create GitHub release or tag repo with version
- [x] Repeat for all (4) repositories

Builds
- [x] Pause build pipeline
- [NA] If releasing dev branch, bump VERSION in dev branch
- [NA] If releasing dev branch, create new pipeline for next release

ISO Distribution
- [x] ISO is uploaded
- [x] ISO download speed check
- [x] Remove access to old ISOs
- [x] Kickoff website job

Cloud Distribution
- [ ] Publish AMI 

Social
- [x] Blog post
- [x] Twitter
- [x] GitHub Discussions

Finish
- [ ] Close GitHub project
- [NA] If releasing dev branch, create the next GitHub project
