### ISSUE TITLE
2.3.70 Checklist

### ISSUE THREAD

**Issue by TOoSmOotH** [Security-Onion-Solutions/securityonion#5108]
This release checklist is important for ensuring consistently high-quality releases are provided to the user base. The checklist is relevant for both Upgrades and Patches.

Prepare release
- [NA] If releasing a non-dev branch, create new GitHub project.
- [NA] If releasing a non-dev branch, create the new branch.
- [NA] If releasing a non-dev branch, update the VERSION file to the next minor increment (Ex: 2.3.72 -> 2.3.73)
- [NA] If releasing a non-dev branch, clear out HOTFIX file.
- [NA] If releasing a non-dev branch, create new pipeline based on the new branch (consider images, soc, and main repos)
- [NA] Update Kibana dashboards and index patterns (IMPORTANT: remember to  escalate at least one alert first)

Test
- [x] Analyst Workstation Install Network (JPP)
- [x] Airgap Upgrade Standalone() (JPP)
- [x] Airgap Upgrade Distributed(MKR)
- [x] Network Upgrade Distributed (RWW)
- [x] Network Upgrade Eval (RWW)
- [x] Network Upgrade Standalone (SS+RWW, JPP)
- [x] Network Upgrade Import (RWW)
- [x] Upgrade Production (MKR)
- [x] AMI installation (JBE)

Documentation
- [x] All affected RTD pages are updated
- [x] Update release notes - Search ISO build output for "TODO" after all issues have been closed and at least one ISO has then built.
- [x] README.md is updated

ISO Prep
- [x] .sig is added to GitHub
- [x] Hashes are updated in GitHub - Search ISO build output for "TODO"

Revision Control (so, soc, images, tests)
- [x] Create and merge PR to master for the changes
- [NA] If releasing a non-dev branch, merge master into dev
- [x] Remove obsolete branches
- [x] Create GitHub release or tag repo with version
- [x] Repeat for all (4) repositories

Builds
- [x] Pause build pipeline
- [x] If releasing dev branch, bump VERSION in dev branch
- [x] If releasing dev branch, create new pipeline for next release

ISO Distribution
- [x] ISO is uploaded
- [x] ISO download speed check
- [ ] Remove access to old ISOs
- [x] Kickoff website job

Cloud Distribution
- [x] Publish AWS Image to Marketplace
- [ ] Publish Azure Image to Marketplace

Social
- [x] Blog post
- [x] Twitter
- [x] GitHub Discussions

Finish
- [ ] Close GitHub project
- [x] If releasing dev branch, create the next GitHub project
- [x] Archive build pipeline
