### ISSUE TITLE
2.3.80 Release Checklist

### ISSUE THREAD

**Issue by jertel** [Security-Onion-Solutions/securityonion#5602]
This release checklist is important for ensuring consistently high-quality releases are provided to the user base. The checklist is relevant for both Upgrades and Patches.

Prepare release
- [NA] If releasing a non-dev branch, create new GitHub project.
- [NA] If releasing a non-dev branch, create the new branch.
- [NA] If releasing a non-dev branch, update the VERSION file to the next minor increment (Ex: 2.3.72 -> 2.3.73)
- [NA] If releasing a non-dev branch, clear out HOTFIX file.
- [NA] If releasing a non-dev branch, create new pipeline based on the new branch (consider images, soc, and main repos)
- [ ] Update Kibana dashboards and index patterns (IMPORTANT: remember to  escalate at least one alert first)

Test
- [ ] Analyst Workstation Install Network ()
- [ ] Airgap Upgrade Standalone ()
- [ ] Airgap Upgrade Distributed ()
- [ ] Network Upgrade Distributed ()
- [ ] Network Upgrade Eval ()
- [ ] Network Upgrade Standalone ()
- [ ] Network Upgrade Import ()
- [ ] Upgrade Production ()
- [ ] AMI installation (JBE)
- [ ] AZI installation (JBE)

Documentation
- [ ] All affected RTD pages are updated
- [ ] Update release notes - Search ISO build output for "TODO" after all issues have been closed and at least one ISO has then built.
- [ ] README.md is updated

ISO Prep
- [ ] .sig is added to GitHub
- [ ] Hashes are updated in GitHub - Search ISO build output for "TODO"

Revision Control (so, soc, images, tests)
- [ ] Create and merge PR to master for the changes
- [NA] If releasing a non-dev branch, merge master into dev
- [ ] Remove obsolete branches
- [ ] Create GitHub release or tag repo with version
- [ ] Repeat for all (4) repositories

Builds
- [ ] Pause build pipeline
- [ ] If releasing dev branch, bump VERSION in dev branch
- [ ] If releasing dev branch, create new pipeline for next release

ISO Distribution
- [ ] ISO is uploaded
- [ ] ISO download speed check
- [ ] Remove access to old ISOs
- [ ] Kickoff website job

Cloud Distribution
- [ ] Publish AWS Image to Marketplace
- [ ] Publish Azure Image to Marketplace

Social
- [ ] Blog post
- [ ] Twitter
- [ ] GitHub Discussions

Finish
- [ ] Close GitHub project
- [ ] If releasing dev branch, create the next GitHub project
- [ ] Archive build pipeline
