### ISSUE TITLE
Release 2.3.90 Checklist

### ISSUE THREAD

**Issue by jertel** [Security-Onion-Solutions/securityonion#6219]
This release checklist is important for ensuring consistently high-quality releases are provided to the user base. The checklist is relevant for both Upgrades and Patches.

Prepare release
- [NA] If releasing a non-dev branch, create new GitHub project.
- [NA] If releasing a non-dev branch, create the new branch.
- [NA] If releasing a non-dev branch, update the VERSION file to the next minor increment (Ex: 2.3.72 -> 2.3.73)
- [NA] If releasing a non-dev branch, clear out HOTFIX file.
- [NA] If releasing a non-dev branch, create new pipeline based on the new branch (consider images, soc, and main repos)
- [x] Update Kibana dashboards and index patterns (IMPORTANT: remember to  escalate at least one alert first)
- [x] All dev/hotfix jobs and tests are passing 
- [x] Educate extended group on new release

Test
- [x] Analyst Workstation Install Network (RWW)
- [x] Airgap Upgrade Standalone (MKR)
- [x] Airgap Upgrade Distributed (MKR)
- [x] Network Upgrade Distributed (MKR)
- [x] Managersearch and Heavynode (JPP)
- [x] Network Upgrade Eval (WL)
- [x] Network Upgrade Standalone (JPP)
- [x] Network Upgrade Import (RWW)
- [x] Upgrade Production (MKR)
- [x] AMI installation (JBE)
- [x] AZI installation (JBE)
- [x] GCI installation (JBE)

Documentation
- [x] All affected RTD pages are updated
- [x] Update release notes - Search ISO build output for "TODO" after all issues have been closed and at least one ISO has then built.
- [x] README.md is updated

ISO Prep
- [x] .sig is added to GitHub
- [x] Hashes are updated in GitHub - Search ISO build output for "TODO"
- [x] Correct date in VERIFY_ISO.md

Revision Control (so, soc, images, tests)
- [x] Create PR to master for the changes
- [NA] If releasing a non-dev branch, merge master into dev
- [x] Remove obsolete branches
- [x] Merge PR to master for changes
- [x] Create GitHub release or tag repo with version
- [x] Repeat for all (4) repositories

Builds
- [x] Pause build pipeline
- [x] If releasing dev branch, bump VERSION in dev branch
- [x] If releasing dev branch, create new pipeline for next release

ISO Distribution
- [x] ISO is uploaded
- [x] ISO download speed check
- [x] Kickoff website job

Cloud Distribution
- [x] Publish AWS Image to Marketplace
- [x] Publish Azure Image to Marketplace

Social
- [x] Blog post
- [x] Twitter
- [x] GitHub Discussions

Finish
- [x] Close GitHub project
- [x] If releasing dev branch, create the next GitHub project
- [x] Archive build pipeline
