### ISSUE TITLE
2.3.100 Checklist

### ISSUE THREAD

**Issue by TOoSmOotH** [Security-Onion-Solutions/securityonion#6979]
This release checklist is important for ensuring consistently high-quality releases are provided to the user base. The checklist is relevant for both Upgrades and Patches.

Prepare release
- [NA] If releasing a non-dev branch, create new GitHub project
- [NA] If releasing a non-dev branch, create the new branch
- [NA] If releasing a non-dev branch, update the VERSION file to the next minor increment (Ex: 2.3.72 -> 2.3.73)
- [NA] If releasing a non-dev branch, clear out HOTFIX file
- [NA] If releasing a non-dev branch, create new pipeline based on the new branch (consider images, soc, and main repos)
- [x] Update Kibana dashboards and index patterns (IMPORTANT: remember to  escalate at least one alert first)
- [x] If updating Kibana dashboards and index patterns, make sure that `soup` will apply those updates as necessary
- [x] Educate extended group on new release
- [x] If doing a full release, generate screenshot tour
- [x] All affected RTD pages are updated
- [x] Update release notes - Search ISO build output for "TODO" after all issues have been closed and at least one ISO has then built.
- [x] Ensure ISO and cloud jobs have completed _after_ all changes have been pushed
- [x] Verify dev jobs are not yet paused, all are passing

Test
- [x] Verify automated tests are passing 
- [x] Review logs
- [x] Analyst Workstation Install Network (DLB)
- [x] Airgap Upgrade Standalone (MKR)
- [x] Airgap Upgrade Distributed (MKR)
- [x] Network Upgrade Distributed (MKR)
- [x] Managersearch and Heavynode (WL)
- [x] Network Upgrade Eval (DLB)
- [x] Network Upgrade Standalone (DLB)
- [x] Network Upgrade Import (DLB)
- [x] Upgrade Production ()
- [x] AMI installation (JBE)
- [x] AZI installation (JBE)
- [x] GCI installation (JBE)
- [x] WebApp Security Tests (JB)

ISO Prep (Do not start this step until the above have been completed)
- [x] Pause build pipeline
- [x] Locate and confirm new ISO file successfully built
- [x] .sig is added to GitHub
- [x] Hashes are updated in GitHub - Search ISO build output for "TODO"
- [x] README.md is updated with new version
- [x] Correct date in VERIFY_ISO.md
- [x] ISO is uploaded
- [x] ISO download speed check

Build and Project Maintenance
- [x] Repeat for the following repositories:  so, soc, images, tests, build
  - [x] Create PR to master for the changes
  - [x] Merge PR to master for changes
  - [NA] If releasing a non-dev branch, merge master into dev
  - [x] Remove obsolete branches
  - [x] Create GitHub release or tag repo with version
- [x] If releasing dev branch, bump VERSION in dev branch
- [x] If releasing dev branch, create new pipeline for next release
- [x] Archive build pipeline
- [x] If releasing dev branch, create the next GitHub project
- [x] Close GitHub project

Distribution
- [x] Publish AWS Image to Marketplace
- [x] Publish Azure Image to Marketplace
- [x] Publish notices (Twitter, GitHub, Blog, etc)
- [x] Kickoff website job
