### ISSUE TITLE
CHECKLIST Blank template

### ISSUE THREAD

**Issue by TOoSmOotH** [Security-Onion-Solutions/securityonion#7291]
This release checklist is important for ensuring consistently high-quality releases are provided to the user base. The checklist is relevant for all release types.

Prepare release
- [ ] If releasing a non-dev branch, create new GitHub project (skip for hotfixes)
- [ ] If releasing a non-dev branch, create the new branch (use hotfix/2.x.y for hotfixes, or patch/2.x.y for full patch releases)
- [ ] If releasing a non-dev branch, update the VERSION file to the next minor increment (Ex: 2.3.72 -> 2.3.73) (Or update HOTFIX file for hotfixes)
- [ ] If releasing a non-dev branch, clear out HOTFIX file (skip for hotfixes)
- [ ] If releasing a non-dev branch, create new pipeline based on the new branch (consider images, soc, and main repos)
- [ ] Update Kibana dashboards and index patterns (IMPORTANT: remember to  escalate at least one alert first)
- [ ] If updating Kibana dashboards and index patterns, make sure that `soup` will apply those updates as necessary
- [ ] Educate extended group on new release
- [ ] If doing a full release, generate screenshot tour
- [ ] All affected RTD pages are updated
- [ ] Update release notes - Search ISO build output for "TODO" after all issues have been closed and at least one ISO has then built.
- [ ] Ensure ISO and cloud jobs have completed _after_ all changes have been pushed
- [ ] Verify dev (or hotfix or patch) jobs are not yet paused, all are passing

Test
- [ ] Verify automated tests are passing 
- [ ] Review logs
- [ ] Analyst Workstation Install Network (skip for hotfixes)
- [ ] Airgap Upgrade Standalone (MKR)
- [ ] Airgap Upgrade Distributed (MKR)
- [ ] Network Upgrade Distributed (MKR)
- [ ] Managersearch and Heavynode (WL)
- [ ] Network Upgrade Eval (DLB)
- [ ] Network Upgrade Standalone (DLB)
- [ ] Network Upgrade Import (DLB)
- [ ] Upgrade Production ()
- [ ] AMI installation (skip for hotfixes)
- [ ] AZI installation (skip for hotfixes)
- [ ] GCI installation (skip for hotfixes)
- [ ] WebApp Security Tests ()

ISO Prep (Do not start this step until the above have been completed)
- [ ] Pause build pipeline
- [ ] Locate and confirm new ISO file successfully built
- [ ] .sig is added to GitHub
- [ ] Hashes are updated in GitHub - Search ISO build output for "TODO"
- [ ] README.md is updated with new version
- [ ] Correct date in VERIFY_ISO.md
- [ ] ISO is uploaded
- [ ] ISO download speed check

Build and Project Maintenance
- [ ] Repeat for the following repositories:  so, soc, images, tests, build (only `so` for hotfixes)
  - [ ] Create PR to master for the changes
  - [ ] Merge PR to master for changes
  - [ ] If releasing a patch or hotfix branch, merge master into dev
  - [ ] Remove obsolete branches
  - [ ] Create GitHub release or tag repo with version
- [ ] If releasing dev branch, bump VERSION in dev branch
- [ ] If releasing dev branch, create new pipeline for next release
- [ ] Archive build pipeline (skip for hotfixes)
- [ ] If releasing dev branch, create the next GitHub project
- [ ] Close GitHub project (skip for hotfixes)

Distribution
- [ ] Publish AWS Image to Marketplace (skip for hotfixes)
- [ ] Publish Azure Image to Marketplace (skip for hotfixes)
- [ ] Publish notices (Twitter, GitHub, Blog - tag as release, etc)
- [ ] Kickoff website job (skip for hotfixes)
